[tool.black]
target-version = ['py36', 'py37', 'py38', 'py39']
line-length = 120
include_trailing_comma = false

[tool.pylint.format]
max-line-length = 120

[tool.pylint.MASTER]
init-hook="import os, sys; sys.path.insert(0, os.path.abspath(os.path.dirname('.')))"
ignore = '''.git,
'''

[tool.pylint.tests]
disable = '''
        missing-module-docstring,
        missing-function-docstring
'''
