[tool.black]
target-version = ['py36', 'py37', 'py38', 'py39']
line-length = 120
include_trailing_comma = false

[tool.pylint.format]
max-line-length = 120

[tool.pylint.MASTER]
ignore = '''.git,
        validate_bases.py
'''

[tool.pylint.tests]

disable = '''missing-module-docstring,
        missing-function-docstring
'''
